services:
  postgres:
    image: postgres:18
    container_name: maptap-postgres

    environment:
      POSTGRES_DB: maptap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "9090:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    restart: unless-stopped

volumes:
  postgres_data: