server.port=8888
#spring.profiles.active=native

spring.application.name=config-server

#spring.cloud.config.server.native.search-locations=file:///Users/nihalramtripathi/Spring/map-tap-config-repo


spring.cloud.config.server.git.uri=file:///Users/nihalramtripathi/Spring/map-tap-config-repo

spring.cloud.config.server.git.search-paths=global,auth-service
#spring.cloud.config.server.git.search-paths=global,user-service,product-service,order-service,api-gateway
